"""Email manager scorecards via Walmart internal SMTP relay.

Email addresses are derived from manager names (first.last@wal-mart.com)
with optional overrides in manager_emails.cfg.

Usage:
    uv run python email_scorecards.py           # send all
    uv run python email_scorecards.py --dry-run  # preview only, no send
"""
from __future__ import annotations

import configparser
import logging
import re
import smtplib
import sys
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from data import load_data
from attendance_data import load_attendance
from checkin_data import load_checkins
from points_data import load_points
from pto_data import load_pto
from scorecard_data import get_manager_scorecard, get_scorecard_summary

logger = logging.getLogger(__name__)

CFG_PATH = Path(__file__).parent / "manager_emails.cfg"


def _load_config() -> configparser.ConfigParser:
    cfg = configparser.ConfigParser()
    cfg.read(CFG_PATH)
    return cfg


def _derive_email(name: str) -> str:
    """Turn 'John Smith' into 'john.smith@wal-mart.com'."""
    clean = re.sub(r"[^a-zA-Z\s-]", "", name).strip().lower()
    parts = clean.split()
    if len(parts) >= 2:
        return f"{parts[0]}.{parts[-1]}@wal-mart.com"
    return f"{clean}@wal-mart.com"


def get_manager_email(name: str, cfg: configparser.ConfigParser) -> str:
    """Return configured override or auto-derived email."""
    override = cfg.get("emails", name, fallback="")
    return override.strip() if override.strip() else _derive_email(name)


def _render_scorecard_email(manager: str, data: dict) -> str:
    """Generate a clean HTML email body for one manager's scorecard."""
    now = datetime.now().strftime("%B %d, %Y")
    cbl   = data["cbl"]
    att   = data["attendance"]
    chk   = data["checkins"]
    pts   = data["points"]
    pto   = data["pto"]

    def metric_row(label: str, value: int, color: str) -> str:
        flag = "&#9888;" if value > 0 else "&#10003;"
        style = f"color:{color};font-weight:bold" if value > 0 else "color:#2a8703"
        return (
            f'<tr><td style="padding:8px 16px;border-bottom:1px solid #f0f0f0">{label}</td>'
            f'<td style="padding:8px 16px;border-bottom:1px solid #f0f0f0;text-align:center;{style}">{flag} {value}</td></tr>'
        )

    total = cbl["total"] + att["total"] + chk["total"] + pts["total"]
    banner_color = "#2a8703" if total == 0 else "#ea1100" if total > 10 else "#995213"
    status_msg   = "All Clear! &#127881;" if total == 0 else f"{total} Open Items Require Attention"

    return f"""
    <div style="font-family:'Segoe UI',Arial,sans-serif;max-width:600px;margin:0 auto;background:#f8f9fa">
      <div style="background:#0053e2;padding:24px 32px">
        <div style="color:white;font-size:22px;font-weight:900;letter-spacing:1px">PHL5 COMPLIANCE</div>
        <div style="color:rgba(255,255,255,0.8);font-size:13px;margin-top:4px">Manager Scorecard &mdash; {now}</div>
      </div>

      <div style="background:{banner_color};padding:14px 32px;color:white;font-weight:bold;font-size:15px">
        {manager} &mdash; {status_msg}
      </div>

      <div style="background:white;padding:24px 32px">
        <table style="width:100%;border-collapse:collapse;font-size:14px">
          <thead>
            <tr style="background:#041f41;color:white">
              <th style="padding:10px 16px;text-align:left">Metric</th>
              <th style="padding:10px 16px;text-align:center">Open Items</th>
            </tr>
          </thead>
          <tbody>
            {metric_row('&#128218; CBL Pending', cbl['total'], '#0053e2')}
            {metric_row('&#128197; Attendance Exceptions', att['total'], '#995213')}
            {metric_row('&#9989; Check-Ins Needed', chk['total'], '#ea1100')}
            {metric_row('&#9888; Associates at Points 5+', pts['total'], '#7f1d1d')}
            {metric_row('&#128203; Time Off Requests', pto['total'], '#2a8703')}
          </tbody>
        </table>
      </div>

      <div style="background:#f0f4ff;padding:16px 32px;border-top:3px solid #0053e2">
        <p style="font-size:12px;color:#555;margin:0">
          This scorecard is auto-generated by the PHL5 Compliance Dashboard.
          Please do not reply to this email.
        </p>
      </div>
    </div>
    """


def send_all_scorecards(dry_run: bool = False) -> dict:
    """Send HTML scorecard emails to all managers. Returns a result summary."""
    cfg = _load_config()
    smtp_host   = cfg.get("settings", "smtp_host",    fallback="smtpout.wal-mart.com")
    smtp_port   = int(cfg.get("settings", "smtp_port", fallback="25"))
    from_addr   = cfg.get("settings", "from_address", fallback="phl5-compliance@wal-mart.com")
    reply_to    = cfg.get("settings", "reply_to",     fallback="")

    cbl = load_data()
    att = load_attendance()
    chk = load_checkins()
    pts = load_points()
    pto = load_pto()

    summary = get_scorecard_summary(cbl, att, chk, pts, pto)
    managers = [r["manager"] for r in summary["rows"]]

    sent, failed, skipped = [], [], []

    for manager in managers:
        email = get_manager_email(manager, cfg)
        data  = get_manager_scorecard(manager, cbl, att, chk, pts, pto)
        html  = _render_scorecard_email(manager, data)

        if dry_run:
            logger.info(f"[DRY RUN] Would email {manager} -> {email}")
            skipped.append({"manager": manager, "email": email})
            continue

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"PHL5 Compliance Scorecard — {manager} — {datetime.now().strftime('%b %d, %Y')}"
        msg["From"]    = from_addr
        msg["To"]      = email
        if reply_to:
            msg["Reply-To"] = reply_to
        msg.attach(MIMEText(html, "html"))

        try:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=15) as server:
                server.sendmail(from_addr, [email], msg.as_string())
            logger.info(f"Sent scorecard to {manager} <{email}>")
            sent.append({"manager": manager, "email": email})
        except Exception as exc:
            logger.warning(f"Failed to email {manager} <{email}>: {exc}")
            failed.append({"manager": manager, "email": email, "error": str(exc)})

    return {"sent": sent, "failed": failed, "skipped": skipped, "dry_run": dry_run}


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    dry = "--dry-run" in sys.argv
    result = send_all_scorecards(dry_run=dry)
    print(f"\nSent: {len(result['sent'])} | Failed: {len(result['failed'])} | Skipped: {len(result['skipped'])}")
